# Assignment 2 IRS - With Synonyms

Information retrieval is the process of obtaining information system resources that are relevant to an information need from a collection of those resources. The core purpose of this assignment is to give you the flavor of IRS. You need to follow some steps listed below and in the end, you'll be able to build your own small IRS. So, let's start.

In [1]:
# required imports
import numpy as np
import fnmatch
import os


Suppose we have 3 files containing data :

### File Contents

!["This is my book" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/f1.png?raw=true)
!["This is my pen" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/f2.png?raw=true)
!["This is book is intersting" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/f3.png?raw=true)

# Step 1 Create Files with Dummy data

You have to create few files with dummy data of your own choice as shown above.

# Step 2 Traverse Directories

 Now, You have to traverse the directories and store all the files into a dict type variable(files_dict). 

In [2]:
# Here we have initialized some variables, you can add more if required.

file_count = 0             # file_count to count number of files
files_dict = {}            # files_dic to store count of every file    
unique_word_set = set()    # unique_word_set to store all the unique words in a set


In [3]:
#Your code starts here 
path = r"C:\Users\hp\Downloads\Assignmnet 2 - IRS\files" #path of folder where files are placed
files = [f for f in os.listdir(path)]# using os method listdir to get count
file_count = len(files)

def dict_files(path): #function to to store count of every file   
    files = {}
    i = 0
    for filename in os.listdir(path): # iterate over each file of the directory of specific path
        file_path = os.path.join(path,filename) #create file path
        if os.path.isfile(file_path) and fnmatch.fnmatch(filename, '*.txt'): #check wheather its a file or not with an extension of txt only
            files[filename] = i #assign dictionary a key with specific value
            i +=1
    return files # return files dictionary
files_dict= dict_files(path)

#Your code ends here       

Displaying the count of files.

In [4]:
print("\nTotal Number  of files\n", file_count)


Total Number  of files
 6


Displaying Dictionary containing all files.

In [5]:
print("\nDictionary containing  files\n", files_dict)


Dictionary containing  files
 {'f1.txt': 0, 'f2.txt': 1, 'f3.txt': 2, 'f4.txt': 3, 'f5.txt': 4}


# Step 3 Extract Unique Vocabulary

write code to print all the unique words in every file and store them in a set

In [6]:
#Your code starts here    
def get_vocab(path):
    words = [] #initialize a list to store words
    for filename in os.listdir(path):
        file_path = os.path.join(path,filename)
        if os.path.isfile(file_path) and fnmatch.fnmatch(filename, '*.txt'):
            f = open(file_path) # open specific file 
            get_words = f.read().lower().split() # create an array of words splitted on the basis of space
            words.extend(get_words) #extend the empty word list with the get_word list
    return words
path = r"C:\Users\hp\Downloads\Assignmnet 2 - IRS\files"
words_list = get_vocab(path)
# print(words_list) 
uniq_word_set = set(words_list) #passing the words_list into set so that we get unique vocab 
uniq_word_set
#Your code ends here

{'and', 'book', 'interesting', 'is', 'my', 'pen', 'shoes', 'this', 'umbrella'}

### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o1.png?raw=true)


# Step 4 Create Term Document Matrix

Create Term-Doc-matrix using Bag of word approach.and display its contents initially and finally.

1. Create Term doc matrix such that colmns will be unique words and all the files will be rows
2. Write code to count all the unique words appearances in all the files and store it in a dictionary for words 

In [7]:
#Your code starts here
len_s = len(uniq_word_set)
len_s
term_mtrx = np.zeros((file_count,len_s)) #create a term matrix using numpy with parameters cols and rows, rows are count of files and cols are number of unique words
print(term_mtrx)

i = 0
dict_v = {}
for word in uniq_word_set: # iterate over the uniq_word_set
    dict_v[word] = i # assign a unique value to each key of dictionary
    i+=1
print("\ndictionary of unique words \n",dict_v)

dict_1 = {}
for word in words_list: #iterate the words_list
    if word not in dict_1: 
        dict_1[word] = words_list.count(word) # count the frequency of words and assign them as a value in a dictionary
print("\n dictionary of all words : \n",dict_1)

print("\n dictionary of files \n",files_dict)
#Your code ends here

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]

dictionary of unique words 
 {'and': 0, 'umbrella': 1, 'book': 2, 'shoes': 3, 'this': 4, 'interesting': 5, 'my': 6, 'pen': 7, 'is': 8}

 dictionary of all words : 
 {'this': 4, 'is': 5, 'my': 5, 'book': 2, 'pen': 1, 'interesting': 1, 'umbrella': 2, 'and': 1, 'shoes': 1}

 dictionary of files 
 {'f1.txt': 0, 'f2.txt': 1, 'f3.txt': 2, 'f4.txt': 3, 'f5.txt': 4}


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o2.png?raw=true)

# Step 5 Fill Term Document Matrix

1. Fill the term doc matrix by checking if the unique word exists in a file or not
2. If it exists then substitute a 1 in term_doc_matrix (eg : TERM_DOC_MATRIX[file][word] = 1 ) 
3. Do the same for all the files present in the directory

In [8]:
#Your code starts here    
print("\ndictionary of unique words \n",dict_v)
dict_v
term_mtrx
path = r"C:\Users\hp\Downloads\Assignmnet 2 - IRS\files"
for filename,value in files_dict.items(): # take filename and its corresponding value and iterate the dictionary
    file_path = os.path.join(path,filename)
    if os.path.isfile(file_path) and fnmatch.fnmatch(filename, '*.txt'):
        f = open(file_path) #open each file 
        words_list = f.read().lower().split() # make a list of word in each file
        for word,count in dict_v.items(): #take word and its corresponding count and iterate the dictionary of unique vocab
            if word in words_list: # if word of unique vocb exits in the list of file(words_list)
                term_mtrx[value][count] = 1 # replace zero with 1 at that specific poistion
print(term_mtrx)
                
#Your code ends here


dictionary of unique words 
 {'and': 0, 'umbrella': 1, 'book': 2, 'shoes': 3, 'this': 4, 'interesting': 5, 'my': 6, 'pen': 7, 'is': 8}
[[0. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 1. 0. 1. 1. 1.]
 [0. 0. 1. 0. 0. 1. 1. 0. 1.]
 [0. 1. 0. 0. 1. 0. 1. 0. 1.]
 [1. 1. 0. 1. 1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o4.png?raw=true)


# Step 6 Ask for a user Query

For user query make a column vector of length of all the unique words present in a set

In [9]:
#Your code starts here    
colVector = np.zeros((len_s,1)) # create column vector
print("colVector initially \n",colVector)
#Your code ends here

colVector initially 
 [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o5.png?raw=true)


In [10]:
query = input("\nWrite something for searching:  ")
print("Query is:", query)


Write something for searching:  is my shoes
Query is: is my shoes


### Expected Output

![Expected Output of query](images/Query.png)

# Step 7 Load Synonyms

In [11]:
synonym_file_path = r"C:\Users\hp\Downloads\Assignmnet 2 - IRS\synonyms.txt"
synonyms_dict = {} # dictionary to store synonyms
#your code starts here
file = open(synonym_file_path,"r")
for line in file:
    lst = line.strip().split(":")# remove \n and make a list with 2 strings 1 before : and a string with multiple words after :(colon)
    synonyms_dict[lst[0]] =lst[1].split(",") # list value as 0 index is given as key and string is converted into list by splitting it on basis of "," and list is corresponded value of key
        
        

#your code ends here

print("\nSynonyms Dictionary\n")
synonyms_dict


Synonyms Dictionary



{'write': [' compose', 'draft', 'author', 'create'],
 'file': [' document', 'record', 'dossier', 'report'],
 'example': [' illustration', 'instance', 'sample', 'demonstration'],
 'query': [' question', ' inquiry', ' search', ' request'],
 'synonym': [' equivalent', ' substitute', ' alternate', ' replacement'],
 'retrieve': [' fetch', ' recover', ' obtain', ' bring back'],
 'system': [' framework', ' structure', ' organization', ' arrangement'],
 'search': [' seek', ' look for', ' explore', ' examine'],
 'lost': [' misplaced', ' missing', ' forgotten', ' mislaid'],
 'pen': [' write', ' ink', ' ballpoint', ' fountain'],
 'paper': [' document', ' sheet', ' form', ' letter'],
 'book': [' novel', ' volume', ' publication', ' tome'],
 'read': [' peruse', ' scan', ' study', ' look at'],
 'interesting': [' fascinating', ' engaging', ' intriguing', ' absorbing'],
 'computer': [' machine', ' device', ' processor', ' laptop'],
 'software': [' program', ' application', ' app', ' platform']}

### Expected Output

![Synonym Dict Example](images\Synonym_dict.png)

# Step 8 Extend User Query

In [12]:
expanded_query = []
# Write code to expand the query using synonyms
#your code starts here
query_1 = query.split()
for word in query_1: # check word in query_1 list 
    found = False # set flag
    for key,value in synonyms_dict.items(): # take key value of synonyms_dict and iterate the dictionary
        if word in [v.strip() for v in value]: #check word in list of value , "v.strip() is used to remov space"
            expanded_query.append(word) # append word in the expanded_query
            expanded_query.append(key)  # append key of synonyms_dict in the expanded_query
            found = True
            break
    if not found:
            expanded_query.append(word)
           



#your code ends here

print("Expanded Query")
print(expanded_query)

Expanded Query
['is', 'my', 'shoes']


### Expected Output

![Extended Query](images\Expanded_Query.png)

Now work with extended query and find the relevant documents.

In [13]:
# Check every word of query if it exists in the set of unique words or not
query_l = query.split()
for word in query_l:
    if word in uniq_word_set: # If exists then increment the count of that word in word dictionary
        dict_1[word] +=1 
print(dict_1)


{'this': 4, 'is': 6, 'my': 6, 'book': 2, 'pen': 1, 'interesting': 1, 'umbrella': 2, 'and': 1, 'shoes': 2}


In [16]:
#Your code starts here    
colVector = np.zeros((len_s,1)) # create column vector
expanded_query
col = colVector.T  # convert into 1d row vector
for word,key in dict_v.items():
    if word in expanded_query: #iterate over expanded_query list
        col[0][key] = 1    #fill specific position
colvector = col.T # convert into 1d column vector
print("colVector after query : \n",colvector)

#Your code ends here

colVector after query : 
 [[0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]]


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o6.png?raw=true)


# Step 7 Display Resultant Vector

Display 
1. Resultant vector.
2. Max value in resultant vector.
3. Index of max value in resultant vector.


In [17]:
#Your code starts here  
result = np.dot(term_mtrx,colvector)
print("result\n",result)
max_index = np.argmax(result) 

print("\nmax_index is \n",max_index)#give index with maximum value
print("\n max \n",max(result))
#Your code ends here

result
 [[2.]
 [2.]
 [2.]
 [2.]
 [3.]
 [0.]]

max_index is 
 4

 max 
 [3.]


### Expected Output

!["Expected Output of unique words" - File 1](https://github.com/ahmad-14a/CS-F20-ML/blob/main/IRS-Assignment%201/o7.png?raw=true)


# Step 8 Display the contents of file


Write the code to identify the file_name having maximum value in the resultant vector and display its contents.

In [18]:
#Your code starts here    
max_index
path = r"C:\Users\hp\Downloads\Assignmnet 2 - IRS\files"
swap_dict = {}
for filename,value in files_dict.items():
    swap_dict[value] = filename #swap key values to get easily access to index of file
# print(swap_dict)
if max(result)> 0:
    filename = swap_dict[max_index] #get specific file according to value
    file_path = os.path.join(path,filename)
    if os.path.isfile(file_path) and fnmatch.fnmatch(filename, '*.txt'):
        file = open(file_path,"r")
        read_file = file.read()
        print(f"The string you searched for exist in this {swap_dict[max_index]} file and the contents of the files are : \n {read_file}")
else:
    print("no such word exist in any files")

#Your code ends here

The string you searched for exist in this f5.txt file and the contents of the files are : 
 this is my umbrella and shoes


Congratulations Now you are able to build your own small IRS which can work even if query does not have exact same words.